name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  # [push]
  push:
    branches: ['main']
  repository_dispatch:
    branches: [ "main" ]
    types: [update-posts]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Install NPM packages
        run: npm ci

      - name: Build Next.js App
        run: npm run build

      - name: Export Next.js App
        run: npm run export

      # - name: Archive output directory
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: out
      #     path: out

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./out/

          # server-dir: /home/xs894317/andrew0826.com/public_html/test-wings/
          server-dir: /andrew0826.com/public_html/test-wings/
          protocol: ftps
